#include "opennow/persistence.hpp"
#include "opennow/json_util.hpp"
#include "opennow/logger.hpp"
#include <fstream>
namespace opennow {
bool save_session(const AuthSession& s,const std::string& path){
 json_t* r=json_object(); json_t* p=json_object(); json_t* t=json_object(); json_t* u=json_object();
 json_object_set_new(p,"idp_id",json_string(s.provider.idp_id.c_str()));json_object_set_new(p,"code",json_string(s.provider.code.c_str()));json_object_set_new(p,"display_name",json_string(s.provider.display_name.c_str()));json_object_set_new(p,"streaming_service_url",json_string(s.provider.streaming_service_url.c_str()));json_object_set_new(p,"priority",json_integer(s.provider.priority));
 json_object_set_new(t,"access_token",json_string(s.tokens.access_token.c_str()));json_object_set_new(t,"refresh_token",json_string(s.tokens.refresh_token.c_str()));json_object_set_new(t,"id_token",json_string(s.tokens.id_token.c_str()));json_object_set_new(t,"client_token",json_string(s.tokens.client_token.c_str()));json_object_set_new(t,"auth_client_id",json_string(s.tokens.auth_client_id.c_str()));json_object_set_new(t,"expires_at_ms",json_integer(s.tokens.expires_at_ms));json_object_set_new(t,"client_token_expires_at_ms",json_integer(s.tokens.client_token_expires_at_ms));
 json_object_set_new(u,"user_id",json_string(s.user.user_id.c_str()));json_object_set_new(u,"display_name",json_string(s.user.display_name.c_str()));json_object_set_new(u,"email",json_string(s.user.email.c_str()));
 json_object_set_new(r,"provider",p);json_object_set_new(r,"tokens",t);json_object_set_new(r,"user",u);json_object_set_new(r,"device_id",json_string(s.device_id.c_str()));
 std::ofstream f(path,std::ios::binary|std::ios::trunc);if(!f){json_decref(r);ON_LOGE("storage","failed to open session file for writing path=%s",path.c_str());return false;}f<<dump_json(r);json_decref(r);f.flush();bool ok=f.good();ON_LOGI("storage","session file write path=%s result=%d",path.c_str(),ok?1:0);return ok;
}
bool load_session(AuthSession& s,const std::string& path){std::ifstream f(path,std::ios::binary);if(!f){ON_LOGI("storage","session file not found path=%s",path.c_str());return false;}std::string b((std::istreambuf_iterator<char>(f)),std::istreambuf_iterator<char>());try{JsonPtr r=parse_json(b);json_t* p=json_object_get(r.get(),"provider"),*t=json_object_get(r.get(),"tokens"),*u=json_object_get(r.get(),"user");s.provider.idp_id=js(p,"idp_id");s.provider.code=js(p,"code");s.provider.display_name=js(p,"display_name");s.provider.streaming_service_url=js(p,"streaming_service_url");s.provider.priority=ji(p,"priority");s.tokens.access_token=js(t,"access_token");s.tokens.refresh_token=js(t,"refresh_token");s.tokens.id_token=js(t,"id_token");s.tokens.client_token=js(t,"client_token");s.tokens.auth_client_id=js(t,"auth_client_id");s.tokens.expires_at_ms=(std::int64_t)json_integer_value(json_object_get(t,"expires_at_ms"));s.tokens.client_token_expires_at_ms=(std::int64_t)json_integer_value(json_object_get(t,"client_token_expires_at_ms"));s.user.user_id=js(u,"user_id");s.user.display_name=js(u,"display_name");s.user.email=js(u,"email");s.device_id=js(r.get(),"device_id");bool ok=!s.tokens.access_token.empty();ON_LOGI("storage","session file parsed path=%s bytes=%u usable=%d",path.c_str(),(unsigned)b.size(),ok?1:0);return ok;}catch(const std::exception&e){ON_LOGE("storage","session file parse failed path=%s bytes=%u error=%s",path.c_str(),(unsigned)b.size(),e.what());return false;}catch(...){ON_LOGE("storage","session file parse failed path=%s bytes=%u unknown_error=1",path.c_str(),(unsigned)b.size());return false;}}
}
