#ifndef JANSSON_CONFIG_H
#define JANSSON_CONFIG_H
#define JSON_INLINE __inline
#define JSON_INTEGER_IS_LONG_LONG 1
#define JSON_HAVE_ATOMIC_BUILTINS 0
#define JSON_HAVE_SYNC_BUILTINS 0
#define JSON_HAVE_LOCALECONV 0
#define JSON_PARSER_MAX_DEPTH 2048
#endif
