#include "opennow/gfn_sdp.hpp"
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <set>
#include <vector>

namespace opennow { namespace {
std::string nstr(long long n){char b[48];std::sprintf(b,"%lld",n);return b;}
std::vector<std::string> split(const std::string&s){std::vector<std::string>v;size_t p=0;while(p<s.size()){size_t e=s.find('\n',p);std::string l=s.substr(p,e==std::string::npos?std::string::npos:e-p);if(!l.empty()&&l[l.size()-1]=='\r')l.erase(l.size()-1);v.push_back(l);if(e==std::string::npos)break;p=e+1;}return v;}
std::string join(const std::vector<std::string>&v){std::string s;for(size_t i=0;i<v.size();++i)s+=v[i]+"\r\n";return s;}
bool sw(const std::string&s,const std::string&p){return s.size()>=p.size()&&s.compare(0,p.size(),p)==0;}
std::string repl(std::string s,const std::string&a,const std::string&b){size_t p=0;while((p=s.find(a,p))!=std::string::npos){s.replace(p,a.size(),b);p+=b.size();}return s;}
int attr_int(const std::string&s,const std::string&a,int d){std::string p="a="+a+":";std::vector<std::string>ls=split(s);for(size_t i=0;i<ls.size();++i)if(sw(ls[i],p)){char*e=NULL;long n=std::strtol(ls[i].c_str()+p.size(),&e,0);if(e!=ls[i].c_str()+p.size())return(int)n;}return d;}
int rtpmap_pt(const std::string&l,const char*c){if(!sw(l,"a=rtpmap:"))return 0;size_t sp=l.find(' ',9);if(sp==std::string::npos)return 0;std::string cp=std::string(c)+"/";if(!sw(l.substr(sp+1),cp))return 0;int n=std::atoi(l.c_str()+9);return n>0&&n<128?n:0;}
std::string fmtp(const std::vector<std::string>&ls,int pt){std::string p="a=fmtp:"+nstr(pt);for(size_t i=0;i<ls.size();++i)if(sw(ls[i],p))return ls[i];return std::string();}
std::vector<std::string> fb(const std::vector<std::string>&ls,int pt){std::vector<std::string>o;std::string p="a=rtcp-fb:"+nstr(pt)+" ";for(size_t i=0;i<ls.size();++i)if(ls[i]==p+"nack"||ls[i]==p+"nack pli")o.push_back(ls[i]);return o;}
int h264pt(const std::string&o){std::vector<std::string>ls=split(o);bool inv=false;std::vector<int>pts;for(size_t i=0;i<ls.size();++i){if(sw(ls[i],"m="))inv=sw(ls[i],"m=video");if(inv){int pt=rtpmap_pt(ls[i],"H264");if(pt)pts.push_back(pt);}}for(size_t i=0;i<pts.size();++i)if(fmtp(ls,pts[i]).find("packetization-mode=1")!=std::string::npos)return pts[i];return pts.empty()?96:pts[0];}
std::string media_kind(const std::string&l){if(sw(l,"m=audio "))return"audio";if(sw(l,"m=video "))return"video";if(sw(l,"m=application "))return"application";return std::string();}
std::string offer_mid(const std::string&o,const std::string&m){bool in=false;std::vector<std::string>ls=split(o);for(size_t i=0;i<ls.size();++i){if(sw(ls[i],"m="))in=media_kind(ls[i])==m;if(in&&sw(ls[i],"a=mid:"))return ls[i].substr(6);}return std::string();}
std::string bundle(const std::string&o){std::vector<std::string>ls=split(o);for(size_t i=0;i<ls.size();++i)if(sw(ls[i],"a=group:BUNDLE "))return ls[i];return std::string();}
struct Section{std::string m;std::vector<std::string>l;Section(){}Section(const std::string&mm,const std::string&first):m(mm){l.push_back(first);}};
std::string align(const std::string&a,const std::string&o){std::vector<std::string>sess,cand;std::set<std::string>seen;std::vector<Section>sec;std::vector<std::string>al=split(a);for(size_t i=0;i<al.size();++i){std::string l=al[i];if(sw(l,"m=")){sec.push_back(Section(media_kind(l),l));continue;}if(sw(l,"a=candidate:")){if(seen.insert(l).second)cand.push_back(l);continue;}if(sec.empty())sess.push_back(l);else sec.back().l.push_back(l);}std::string b=bundle(o);bool br=false;for(size_t i=0;i<sess.size();++i)if(!b.empty()&&sw(sess[i],"a=group:BUNDLE ")){sess[i]=b;br=true;}if(!b.empty()&&!br)sess.push_back(b);for(size_t i=0;i<sec.size();++i){std::string mid=offer_mid(o,sec[i].m);if(mid.empty())continue;bool done=false;for(size_t j=0;j<sec[i].l.size();++j)if(sw(sec[i].l[j],"a=mid:")){sec[i].l[j]="a=mid:"+mid;done=true;break;}if(!done&&sec[i].l.size()>1)sec[i].l.insert(sec[i].l.begin()+1,"a=mid:"+mid);}std::vector<Section>ord;std::vector<bool>used(sec.size(),false);std::vector<std::string>ol=split(o);for(size_t oi=0;oi<ol.size();++oi){std::string m=media_kind(ol[oi]);if(m.empty())continue;for(size_t i=0;i<sec.size();++i)if(!used[i]&&sec[i].m==m){ord.push_back(sec[i]);used[i]=true;break;}}for(size_t i=0;i<sec.size();++i)if(!used[i])ord.push_back(sec[i]);if(!ord.empty())ord[0].l.insert(ord[0].l.end(),cand.begin(),cand.end());for(size_t i=0;i<ord.size();++i)sess.insert(sess.end(),ord[i].l.begin(),ord[i].l.end());return join(sess);}
std::string val(const std::string&s,const std::string&p){std::vector<std::string>ls=split(s);for(size_t i=0;i<ls.size();++i)if(sw(ls[i],p))return ls[i].substr(p.size());return std::string();}
std::string host(std::string u){size_t p=u.find("://");if(p!=std::string::npos)u.erase(0,p+3);size_t sl=u.find('/');if(sl!=std::string::npos)u.resize(sl);if(!u.empty()&&u[0]=='['){size_t e=u.find(']');return e==std::string::npos?u:u.substr(1,e-1);}size_t c=u.find(':');if(c!=std::string::npos)u.resize(c);return u;}
std::string gfn_ip(const std::string&h){int a,b,c,d;if(std::sscanf(h.c_str(),"%d-%d-%d-%d",&a,&b,&c,&d)==4&&a<=255&&b<=255&&c<=255&&d<=255)return nstr(a)+"."+nstr(b)+"."+nstr(c)+"."+nstr(d);return h;}
void add(std::vector<std::string>&v,const std::string&s){v.push_back(s);}
}
RiInputCaps parse_ri_caps(const std::string&o){RiInputCaps c;c.threshold_ms=std::max(1,std::min(5000,attr_int(o,"ri.partialReliableThresholdMs",16)));c.hid_mask=(unsigned)attr_int(o,"ri.hidDeviceMask",0);c.gamepad_mask=(unsigned)attr_int(o,"ri.enablePartiallyReliableTransferGamepad",1);c.hid_partial_mask=(unsigned)attr_int(o,"ri.enablePartiallyReliableTransferHid",0);return c;}
std::string prepare_gfn_offer(std::string o,const std::string&url,const std::string&hint){std::string ip=gfn_ip(hint.empty()?host(url):hint);if(!ip.empty())o=repl(o,"0.0.0.0",ip);return o;}
std::string adapt_gfn_answer(const std::string&a,const std::string&o,const StreamConfig&cfg){int pt=h264pt(o);std::vector<std::string>ol=split(o);std::string of=fmtp(ol,pt);std::vector<std::string>ofs=fb(ol,pt);std::string redmap,redfmt;bool oa=false;for(size_t i=0;i<ol.size();++i){const std::string&l=ol[i];if(sw(l,"m=")){oa=sw(l,"m=audio");continue;}if(oa&&sw(l,"a=rtpmap:63 ")&&(l.find("red/48000")!=std::string::npos||l.find("RED/48000")!=std::string::npos))redmap=l;else if(oa&&sw(l,"a=fmtp:63 "))redfmt=l;}std::vector<std::string>out;bool iv=false,ia=false,bw=false,feedback=false,red=false;std::string ps=nstr(pt);std::vector<std::string>al=split(a);for(size_t i=0;i<al.size();++i){const std::string&l=al[i];if(sw(l,"m=")){iv=sw(l,"m=video");ia=sw(l,"m=audio");if(iv){out.push_back("m=video 9 UDP/TLS/RTP/SAVPF "+ps);continue;}if(ia){out.push_back(redmap.empty()?"m=audio 9 UDP/TLS/RTP/SAVPF 111":"m=audio 9 UDP/TLS/RTP/SAVPF 111 63");continue;}if(sw(l,"m=application")){out.push_back("m=application 9 UDP/DTLS/SCTP webrtc-datachannel");continue;}}if(ia&&!red&&sw(l,"a=rtpmap:111")){out.push_back(l);if(!redmap.empty()){out.push_back(redmap);if(!redfmt.empty())out.push_back(redfmt);}red=true;continue;}if(iv&&sw(l,"c=IN ")){out.push_back(l);out.push_back("b=AS:"+nstr(cfg.bitrate_kbps));bw=true;continue;}if(iv&&sw(l,"a=rtcp-fb:96")){if(!feedback){if(ofs.empty()){out.push_back("a=rtcp-fb:"+ps+" nack");out.push_back("a=rtcp-fb:"+ps+" nack pli");}else out.insert(out.end(),ofs.begin(),ofs.end());feedback=true;}continue;}if(iv&&sw(l,"a=fmtp:96")){out.push_back(of.empty()?"a=fmtp:"+ps+" level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f":of);continue;}if(iv&&sw(l,"a=rtpmap:96")){out.push_back("a=rtpmap:"+ps+" H264/90000");continue;}if(iv&&sw(l,"a=ssrc:"))continue;if(iv&&sw(l,"a=sendrecv")){out.push_back("a=recvonly");continue;}out.push_back(l);}if(!bw)for(size_t i=0;i<out.size();++i)if(sw(out[i],"m=video")){out.insert(out.begin()+i+1,"b=AS:"+nstr(cfg.bitrate_kbps));break;}return align(join(out),o);}
std::string build_nvst_sdp(const std::string&a,const StreamConfig&c,const RiInputCaps&rc){std::string u=val(a,"a=ice-ufrag:"),p=val(a,"a=ice-pwd:"),fp=val(a,"a=fingerprint:sha-256 ");int max=std::max(4000,c.bitrate_kbps),initial=std::min(max,4000);std::vector<std::string>l;const char*fixed[]={"v=0","o=SdpTest test_id_13 14 IN IPv4 127.0.0.1","s=-","t=0 0"};for(size_t i=0;i<4;++i)add(l,fixed[i]);add(l,"a=general.icePassword:"+p);add(l,"a=general.iceUserNameFragment:"+u);add(l,"a=general.dtlsFingerprint:"+fp);const char*video[]={"m=video 0 RTP/AVP","a=msid:fbc-video-0","a=vqos.fec.rateDropWindow:10","a=vqos.fec.minRequiredFecPackets:2","a=vqos.drc.minRequiredBitrateCheckEnabled:1","a=vqos.fec.repairMinPercent:5","a=vqos.fec.repairPercent:10","a=vqos.fec.repairMaxPercent:20","a=vqos.dynamicStreamingMode:3","a=vqos.bllFec.enable:0","a=vqos.drc.enable:1","a=video.dx9EnableNv12:1","a=video.dx9EnableHdr:0","a=vqos.qpg.enable:1","a=vqos.resControl.qp.qpg.featureSetting:7","a=bwe.useOwdCongestionControl:1","a=video.enableRtpNack:1","a=vqos.bw.txRxLag.minFeedbackTxDeltaMs:20","a=vqos.drc.bitrateIirFilterFactor:8","a=video.packetSize:1140","a=packetPacing.minNumPacketsPerGroup:1","a=vqos.adjustStreamingFpsDuringOutOfFocus:0","a=vqos.resControl.cpmRtc.ignoreOutOfFocusWindowState:1","a=vqos.resControl.perfHistory.rtcIgnoreOutOfFocusWindowState:1","a=vqos.resControl.cpmRtc.featureMask:3","a=packetPacing.numGroups:2","a=packetPacing.maxDelayUs:500","a=packetPacing.minNumPacketsFrame:4","a=video.rtpNackQueueLength:128","a=video.rtpNackQueueMaxPackets:64","a=video.rtpNackMaxPacketCount:8"};for(size_t i=0;i<sizeof(video)/sizeof(video[0]);++i)add(l,video[i]);add(l,"a=video.clientViewportWd:"+nstr(c.width));add(l,"a=video.clientViewportHt:"+nstr(c.height));add(l,"a=video.maxFPS:"+nstr(c.fps));add(l,"a=video.initialBitrateKbps:"+nstr(initial));add(l,"a=video.initialPeakBitrateKbps:"+nstr(initial));add(l,"a=vqos.bw.maximumBitrateKbps:"+nstr(max));add(l,"a=vqos.bw.minimumBitrateKbps:4000");const char*tail[]={"a=video.maxNumReferenceFrames:2","a=video.mapRtpTimestampsToFrames:1","a=video.encoderCscMode:3","a=video.encoderHdrCscMode:4","a=video.dynamicRangeMode:0","a=video.bitDepth:8","a=video.scalingFeature1:0","a=video.prefilterParams.prefilterMode:0","a=video.prefilterParams.prefilterModel:0","a=video.prefilterParams.denoiseLevel:0","a=video.prefilterParams.sharpnessLevel:0","m=audio 0 RTP/AVP","a=msid:audio","m=mic 0 RTP/AVP","a=msid:mic","a=rtpmap:0 PCMU/8000","m=application 0 RTP/AVP","a=msid:input_1"};for(size_t i=0;i<sizeof(tail)/sizeof(tail[0]);++i)add(l,tail[i]);add(l,"a=ri.partialReliableThresholdMs:"+nstr(std::min(rc.threshold_ms,16)));add(l,"a=ri.hidDeviceMask:"+nstr(rc.hid_mask));add(l,"a=ri.enablePartiallyReliableTransferGamepad:"+nstr(rc.gamepad_mask));add(l,"a=ri.enablePartiallyReliableTransferHid:"+nstr(rc.hid_partial_mask));std::string s;for(size_t i=0;i<l.size();++i)s+=l[i]+'\n';return s;}
std::string build_manual_candidate(const std::string&url,const std::string&hint,int port,int foundation){std::string ip=gfn_ip(hint.empty()?host(url):hint);if(ip.empty()||port<=0)return std::string();return "a=candidate:"+nstr(foundation)+" 1 UDP 2130706431 "+ip+" "+nstr(port)+" typ host";}
}
